run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - bodyclose
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true # отключаем требование doc-комментариев на каждый экспортируемый идентификатор
